dataset:
  src: data/data/qm9
  train_size: 112000
  val_size: 10000
  test_size: 10000

task:
  dataset: qm9
  description: "A dataset of ~130k organic molecules with 16 regression targets from https://arxiv.org/abs/1703.00564."
  type: regression
  metric: mae_ratio
  labels:
    - dipole moment
    - isotropic polarizability
    - energy of homo
    - energy of lumo
    - difference between homo and lumo
    - electronic spatial extent
    - zero point vibrational energy
    - internal energy at 0K
    - internal energy at 298.15K
    - enthalpy at 298.15K
    - free energy at 298.15K
    - heat capacity at 298.15K
    - atomization energy at 0K
    - atomization energy at 298.15K
    - atomization enthalpy at 298.15K
    - atomization free energy at 298.15K
  label_index: 0
