dataset:
  src: data/data/iso17
  train_size: 400000
  val_size: 4000
  test_size: 101000

task:
  dataset: iso17
  description: "A dataset of 129 organic molecules each containing 5,000 conformational geometries, energies and forces with a resolution of 1 femtosecond in the molecular dynamics trajectories."
  type: regression
  metric: mae
  labels:
    - total energy
