model: fairchem.core.models.gemnet_oc.gemnet_oc.GemNetOCBackbone

num_spherical: 7
num_radial: 128
num_blocks: 4
emb_size_atom: 256
emb_size_edge: 512
emb_size_trip_in: 64
emb_size_trip_out: 64
emb_size_quad_in: 32
emb_size_quad_out: 32
emb_size_aint_in: 64
emb_size_aint_out: 64
emb_size_rbf: 16
emb_size_cbf: 16
emb_size_sbf: 32
num_before_skip: 2
num_after_skip: 2
num_concat: 1
num_atom: 3
num_output_afteratom: 3
cutoff: 12.0
cutoff_qint: 12.0
cutoff_aeaint: 12.0
cutoff_aint: 12.0
max_neighbors: 30
max_neighbors_qint: 8
max_neighbors_aeaint: 20
max_neighbors_aint: 100
rbf:
  name: gaussian
envelope:
  name: polynomial
  exponent: 5
cbf:
  name: spherical_harmonics
sbf:
  name: legendre_outer
extensive: True
output_init: HeOrthogonal
activation: silu

regress_forces: True
regress_stress: True
direct_forces: True
direct_stress: True
forces_coupled: True

quad_interaction: False
atom_edge_interaction: False
edge_atom_interaction: False
atom_interaction: False

num_atom_emb_layers: 2
num_global_out_layers: 2
qint_tags: [1, 2]
otf_graph: True
use_pbc_single: True

use_torch_sparse: False
